export function PrivacyPolicy() {
  return (
    <div className="space-y-6 text-white/70 font-body leading-relaxed text-left">
      <p>
        At FillAI, we take your privacy seriously. This Privacy Policy explains how we collect, use, and protect your information when you use our browser extension and website.
      </p>
      <h4 className="text-lg font-bold text-white mt-6 mb-2">1. Data Collection</h4>
      <p>
        Your profile data is stored securely on your local machine or synced via your secure browser account. We do not sell your personal data to third parties. When you trigger an autofill using our AI generation, only the relevant form context is securely transmitted to our AI provider (Google Gemini) for the sole purpose of generating your response.
      </p>
      <h4 className="text-lg font-bold text-white mt-6 mb-2">2. Security</h4>
      <p>
        We implement a variety of security measures to maintain the safety of your personal information. All transmitted data is encrypted via Secure Socket Layer (SSL) technology.
      </p>
    </div>
  );
}

export function TermsOfService() {
  return (
    <div className="space-y-6 text-white/70 font-body leading-relaxed text-left">
      <p>
        Welcome to FillAI. By using our service, you agree to these terms. Please read them carefully.
      </p>
      <h4 className="text-lg font-bold text-white mt-6 mb-2">1. Usage</h4>
      <p>
        FillAI is provided "as is". You agree to use it only for lawful purposes and in a way that does not infringe the rights of, restrict, or inhibit anyone else's use and enjoyment of the service.
      </p>
      <h4 className="text-lg font-bold text-white mt-6 mb-2">2. AI Generation Disclaimer</h4>
      <p>
        While our AI strives for accuracy, it is your responsibility to review any content generated by FillAI before submitting it to employers, CRMs, or any other web portals.
      </p>
    </div>
  );
}
